### ISSUE TITLE
Dev build fails when rebuilding presentation

### ISSUE THREAD

**Issue by proff321** [jxnblk/mdx-deck#595]
Hello!  I have a very simple presentation that builds successfully the first time, but then fails to rebuild once a change is made.  If you simply save the file, the build does not fail, but any modification results in the following error:

```
Error: Command failed with exit code 1 (EPERM): gatsby develop --host localhost --port 8000 --open
    at makeError (/app/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/app/node_modules/execa/index.js:112:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

The code is running within a docker container.  Here's the docker-compose file:

```
version: "3.6"
services:
    present:
        image: node
        volumes:
            - ./:/app
        ports:
            - "8000:8000"
        working_dir: /app
        entrypoint: ["npm"]
        command: ["start"]
    npm:
        image: node
        volumes:
            - ./:/app
        working_dir: /app
        entrypoint: ["npm"]
        command: ["--version"]
```

The `present` service issues the following `npm` command as defined in the "package.json" file:

```
"start": "mdx-deck presentation.mdx"
```

The actual presentation, saved as "presentation.mdx", is as follows:

```
# Presentation Title

---

# About Me
````

Here's how to setup and reproduce the issue (docker commands are run with `sudo` on my machine):

1. Install the framework: `docker-compose run --rm npm i -D mdx-deck`
1. Run the presentation service: `docker-compose run --rm --service-ports present`
1. The build will finish and you can see the presentation in the browser of the host
1. Save the "presentation.mdx" file without making any modifications
1. Notice that the `info` statement is logged, but the service remains stable
1. Modify the "presentation.mdx" file and save
1. The error mentioned above appears and the docker service dies

I noticed issue #416 which had a very similar error, but the "package-lock.json" file shows the `gatsby-plugin-compile-es6-packages` package as being installed at version "2.1.0".
